acme_test_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeTestBundle:Default:index }

acme_test2:
    path:     /test2
    defaults: { _controller:  AcmeTestBundle:Default:test2 }