acme_test_post:
    resource: "@AcmeTestBundle/Resources/config/routing/post.yml"
    prefix:   /post

acme_test_homepage:
    path:     /welcome/{name}
    defaults: { _controller: AcmeTestBundle:Default:index }

acme_test2:
    path:     /test2
    defaults: { _controller:  AcmeTestBundle:Default:test2 }