acme_test:
    resource: "@AcmeTestBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

aimeos_shop:
    resource: "@AimeosShopBundle/Resources/config/routing.yml"
    prefix: /